front/src/layouts/MainLayout.vue, front/src/store/index.js
Next to the current task, we show the 3 recent visited tasks.
The recent tasks are sorted by visit time. The most recent is on the left, the oldest on the right. The oldest task will be removed when more than 3 recent tasks will be displayed.
This will make navigating between tasks easier.
=> Show recently visited tasks in the menu bar

front/src/pages/CTF/CTF.vue
When your mouse crosses the credentials, they will instantly unblur.
This is not very useful when your screen is being recorded for example.
Now we add a small delay so you can only unblur the credentials when you explicitly hold your mouse on the credentials.
=> Increase credentials unblur time

docker-compose.yml, front/nginx.conf
CodiMD changed its name to HedgeDoc with the new update.
The nginx config was updated because of the update notes of 1.7.0:
https://github.com/hedgedoc/hedgedoc/releases/tag/1.7.0
I just searched for [HedgeDoc on hub.docker.com](https://hub.docker.com/search?q=hedgedoc&type=image) and picked the most popular one.
I have tested it myself and it seems to work just fine. But maybe you also want to test this before merging, so we can both confirm it will not cause any issues.
=> Change CodiMD 1.6 to HedgeDoc 1.7.2

docker-compose.yml
Previous versions of codimd used imgur to store uploaded images. This behaviour
changed to local filesystem when we upgraded to Hedgedoc.
This commit reverts the uploading feature to the previous behaviour.
This fixes #18
=> pad: set imgur as default upload service

api/src/config/globals.ts, api/src/config/persitent.ts, api/src/config/routes.ts, api/src/controllers/config.controller/update.action.ts, api/src/controllers/settings.controller/get.action.ts, api/src/controllers/task.controller/update.action.ts, api/src/entity/Config.ts, api/src/entity/Task.ts, api/src/migration/1615405149843-SaveFlag.ts, front/quasar.conf.js, front/src/api.js, front/src/components/Task.vue, front/src/store/index.js
After a task is marked as "Solved", the user is asked to enter the flag. The flag will be stored in the database and the user can open it using the context menu. If no flag is provided, nothing will be overwritten. Therefore, it is possible to solve and unsolve a task multiple times without overwriting the current flag.
A global option "store-flag" is added to enable/disable this feature. The default is true.
An API is introduced to query non-private settings, so it will also work for non-admin users.
The "store-flag" setting can also be overwritten by the environment variable CTFNOTE_STORE_FLAG.
For some more context:
We added this feature, because sometimes it is required to create a writeup with flags in order to claim a spot on the scoreboard. However, we sometimes forget to store the …
=> Add feature for storing flag in database

front/src/components/Task/TaskCard.vue
Player chips are added back again as before the "dense" and "ultradense" update.
Similar to https://github.com/JJ-8/CTFNote/commit/76232854b3fbaf550e8101935347292e2bf3386c
As discussed in https://github.com/TFNS/CTFNote/issues/68
=> Add player chips back

api/migrations/39-sort-users.sql
This will prevent jumps in the table when you edit an entry.
=> Sort users by ID

docker-compose.dev.yml, docker-compose.yml
https://github.com/hedgedoc/hedgedoc/releases/tag/1.9.2
https://github.com/hedgedoc/hedgedoc/releases/tag/1.9.1
=> Hedgedoc: upgrade to version 1.9.2

front/src/components/Task/TaskList.vue, front/src/components/Utils/TaskListMenu.vue
If a task is solved, it is moved to the bottom of the view to prioritize the tasks that are not solved yet.
There is also a new checkbox introduced: 'Show my tasks'. This will show only the tasks that you have assigned yourself to.
The 'Hide solved' checkbox now only makes the list shorter, but it is still nice to have.
This is already discussed [here](https://github.com/TFNS/CTFNote/discussions/102#discussioncomment-1541805).
I decided to not implement pinning since it causes confusion when you click the button: it appears that the task has not been marked as 'on it', but actually the row is swapped with a different task because of the ordering. Instead of pinning, I added the 'Show my tasks' filter.
=> Move solved tasks to end of list, add filter for own tasks

api/src/plugins/createTask.ts
Now we first evaluate `ctfnote_private.can_play_ctf` before adding a task.
If it is not true (value can also be `null`), then we do not create and add the pad.
This prevents guests from adding tasks to CTFs they are not allowed to participate in.
=> Limit task creation by access control

front/src/components/Task/TaskTable.vue
This prevents lots of vertical scrolling when there is a long description.
Related to https://github.com/TFNS/CTFNote/issues/111 (see screenshots there).
Also mentioned in #146 and #102
=> Add word wrapping to table layout

docker-compose.dev.yml, docker-compose.yml
1.9.3 release: https://github.com/hedgedoc/hedgedoc/releases/tag/1.9.3
It contains a security update, so updating is recommended:
https://github.com/hedgedoc/hedgedoc/security/advisories/GHSA-q6vv-2q26-j7rx
=> Update Hedgedoc to 1.9.3

docker-compose.yml
Changelog: https://github.com/hedgedoc/hedgedoc/releases/tag/1.9.4
=> Upgrade Hedgedoc to version 1.9.4

front/src/ctfnote/parsers/ctfd.ts
Hey there!
This just fixes a small typo in the CTFd importer hint.
The correct URI is `/api/v1/challenges`, according to https://docs.ctfd.io/docs/api/swagger-ui
=> Fixed URI in ctfd importer hint

docker-compose.dev.yml, docker-compose.yml
Follow-up of the problem #173 
Hedgedoc's build system removes untagged containers -- we cannot rely on them for pinning.
=> Unpin Hedgedoc

api/yarn.lock
I hand-patched the vulnerable dependency to a non-vulnerable version.
I did this by:
1. removing `dicer` and its dependency from the yarn lockfile
2. changing the `dicer` requirement to upgrade its version to 0.3.1
3. running `yarn add` to add `dicer@0.3.1`
4. remove the direct dependency on dicer from package.json
I invited you to a private repository with a PoC script to test the fix.
The container `api` crashes before the patch, now it drops the request
=> Fix CVE-2022-24434

api/package.json, api/yarn.lock
Current fix required to edit the lock file by hand.
This commit adds a "resolutions" key to the package.json file.
This pins this specific dependency to version 0.3.1 without using dubious hacks.
More info about this feature:
https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/
On a different topic : can you rebase PR instead of merging them ? (Click on the downward-pointing arrow before merging)
This makes a prettier git history
=> API: Pin dicer to v0.3.1

front/package.json, front/yarn.lock
I do not know how to test that. At least it still builds :D
We still have @quasar/cli's dependencies, but those are too ancient to be upgraded it seems.
```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ moderate      │ Got allows a redirect to a UNIX socket                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ got                                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=11.8.5                                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @quasar/cli …
```
=> Front: upgrade outdated sub-dependencies

docker-compose.yml
In case of DoS, the container will restart instead of it being down until restarted manually.
As discussed in https://github.com/TFNS/CTFNote/pull/179
=> Enable auto-restart for api and front container

front/src/ctfnote/parsers/ecsc.ts, front/src/ctfnote/parsers/index.ts
With the upcoming [ECSC competition](https://www.ecsc2022.eu/), it is useful to have a special ECSC task parser since some teams will use CTFNote as their note management software, and importing all the tasks yourself is just painful.
This parser parses the JSON output of the `/stats.json` endpoint of the [ECSC gameboard](https://github.com/enisaeu/ecsc-gameboard). The output doesn't contain actual categories, so we use the 'contract' name as the category.
Example JSON output of `/stats.json` to test the parser:
```json
[
{
"task": "First task of first contract",
"contract": "First contract",
"cash": 0,
"solved_by": [
"test"
],
"average_time": "35 seconds"
},
{
"task": "Second task of first contract",
"contract": "First contract",
"cash": 0,
"solved_by": [],
"average_time": null
},
{ …
```
=> Add ECSC task parser

front/src/components/Dialogs/TaskExportDialog.vue, front/src/components/Task/TaskList.vue
All tasks can now be bundled together to create one big document of tasks that can be submitted as a writeup for a CTF. This saves lots of time copying the tasks in a document one by one.
The user can choose to export all tasks or only the solved tasks.
Optionally, the user can supply a team name to add to the writeup since that is often required if you want to submit it to an organization.
The export is done client side using the APIs of Hedgedoc.
This functionality is especially useful for CTFs where you have to submit your writeup very quickly after the competition (for example the [ECSC](https://ecsc.eu/)).
Example of an export:
```md
Balsn CTF 2022
===
Sat, 03 Sep 2022 02:00:00 GMT - Mon, 05 Sep 2022 02:00:00 GMT
Team: Team name
| Task | Flag |
|---|---|
| First Task | FLAG{TEST} |
| …
```
=> Make tasks exportable as Markdown

front/Dockerfile
This fixes CVE-2022-41741 and CVE-2022-41742
https://mailman.nginx.org/archives/list/nginx-announce@nginx.org/message/RBRRON6PYBJJM2XIAPQBFBVLR4Q6IHRA/
The issues do not affect the default configuration.
=> Front: upgrade nginx to 1.22.1

front/package.json, front/yarn.lock
3 vulnerabilities found - Packages audited: 1420
Severity: 2 Moderate | 1 High
Using yarn's upgrade tool will break front.
One of the packages appears to be shipping breaking changes on a minor version number... let's override the resolution of more packages.
=> Front: upgrade dependencies

front/src/ctfnote/parsers/ctfd.ts
The [RCTF platform](https://github.com/redpwn/rctf) uses the same API as [CTFd](https://github.com/CTFd/CTFd), but this is not obvious for the user importing the tasks.
This pull requests adds a parser, that imports the functionality of the CTFdParser but explains api endpoints.
=> Add RCTF Parser basing on CTFD

front/src/ctfnote/ui.ts
Success notifications are blocking the dropdown in the upper right corner, but there is no way to dismiss them.
Now it is possible to dismiss them, just like the error notifications.
=> Make success notifications dismissible

front/src/components/Dialogs/TaskExportDialog.vue
Exporting all tasks may take a while. This is now shown by the loading state of the export button.
Moreover, the dialog now closes when the export is completed.
=> Add loading to Export Tasks

front/src/components/Task/TaskBtnGroup.vue, front/src/components/Task/TaskList.vue, front/src/components/Task/TaskMenu.vue, front/src/components/Utils/TaskListMenu.vue, front/src/ctfnote/tasks.ts
Now it is possible to edit a task directly from within the Hedgedoc view of a task. This is especially useful when handing in the flag when a task is solved, since you don't have to leave the Hedgedoc view anymore.
The context menu works for both the current task it displays, as well as all the tasks in the dropdown menu.
In order to make this possible, the `solveTaskPopup`, `deleteTaskPopup` and `editTaskPopup` have been moved from a `provide` to a global function that can be imported. This allows the use of these functions within every component instead of only the child components of the TaskList.
=> Add context menu to task dropdown

front/src/components/Dialogs/TaskImportDialog.vue, front/src/ctfnote/parsers/htb.ts, front/src/ctfnote/parsers/index.ts
This parses the tasks of the CTF website https://ctf.hackthebox.com/. The tasks can be copied from the network tab. A direct GET-request to the endpoint does not work, since the endpoint requires authentication with a bearer token in the Authorization header.
The number to category mapping seems to be static and comes from the https://ctf.hackthebox.com/api/public/challengeCategories endpoint, which is publicly accessible.
This parser also imports the challenge description. To allow this, the `ParsedTask` type is modified to include an optional `description` field. The object passed to `createTask` is also implicit, to include the description in the object.
This commit also includes small code refactoring:
- The `ParsedTask` type is not duplicated anymore, but imported from …
=> Add HTB parser

front/package.json, front/src/components/Dialogs/TaskExportDialog.vue, front/yarn.lock
This adds the possibility to use a zip archive as the export format. It will add every task as a Markdown file to the zip archive and create an overview file which contains the same introduction as the Markdown export. The original single-markdown export is still possible and the default.
To create the zip archive, the dependency [JSZip](https://www.npmjs.com/package/jszip) is used.
This feature was also already suggested in https://github.com/TFNS/CTFNote/pull/185#pullrequestreview-1095672551.
=> Add zip archive export format

front/src/ctfnote/parsers/index.ts, front/src/ctfnote/parsers/pico.ts
This parses the challenges of the https://play.picoctf.org/ platform.
You have to paste the json of the `/api/challenges/?page_size=500&page=1&event=XX` endpoint manually where `XX` is the ID of the running event.
=> Add picoCTF parser

front/src/ctfnote/parsers/htb.ts
This was newly added to the challenge categories as listed at https://ctf.hackthebox.com/api/public/challengeCategories
=> Add ML category to HTB parser

docker-compose.dev.yml, docker-compose.yml
The release notes of Hedgedoc can be found [here](https://github.com/hedgedoc/hedgedoc/releases).
=> Update Hedgedoc to latest version 1.9.7

api/package.json, api/src/index.ts, api/src/plugins/uploadLogo.ts, api/src/plugins/uploadScalar.ts, api/yarn.lock, front/.eslintrc.js, front/package.json, front/src/components/CTF/Guests.vue, front/src/components/CTF/Info.vue, front/src/components/Task/TaskBadge.vue, front/src/components/Task/TaskList.vue, front/src/css/quasar.variables.scss, front/yarn.lock
I have done an upgrade of all dependencies of both the frontend and the backend. This fixes all dependency vulnerabilities in the project according to `yarn audit`.
The graphql-upload packages has been swapped with graphql-upload-ts, because it is not possible anymore to use graphql-upload due to import issues with TypeScript. Graphql-upload-ts is an drop-in replacement with even less dependencies so less code that can break!
I have tested almost all functionalities of CTFNote by hand and had no issues.
This PR is a successor of https://github.com/TFNS/CTFNote/pull/206.
=> Upgrade dependencies to latest versions

docker-compose.dev.yml, docker-compose.yml
Release notes can be found here: https://github.com/hedgedoc/hedgedoc/releases/tag/1.9.8
Prettier also urgently wanted to replace all `'` with `"` to be consistent :)
=> Update Hedgedoc to 1.9.8

front/src/ctfnote/parsers/angstrom.ts, front/src/ctfnote/parsers/index.ts
Allows to add ångstromCTF challenges from https://angstromctf.com/
I've mimiced the stricter `isValid` tests from the justCTF parser addition PR, but didn't test it afterwards. During the CTF I only had the `isArray` check, but since their platform has problems currently, I can't test it with the stricter checks. But given the pico and justCTF parsers are similar, I'd expect this to still be fine.
=> Add ångstromCTF parser

api/migrations/54-add-discord-integration-enabled.sql, api/src/index.ts, front/graphql.schema.json, front/src/components/CTF/Guests.vue, front/src/ctfnote/models.ts, front/src/ctfnote/settings.ts, front/src/generated/graphql.ts, front/src/graphql/Settings.graphql, front/src/pages/Settings.vue
Implementation of issue #292.
Adds a warning telling you the integration has been disabled
=> Add Discord integration checks to frontend.

.env.example, api/migrations/55-discord-account-invitation-link.sql, api/src/config.ts, api/src/discord/commands.ts, api/src/discord/commands/register.ts, api/src/discord/database/users.ts, api/src/plugins/discordHooks.ts, front/graphql.schema.json, front/src/generated/graphql.ts
=> Add linked account creation from the Discord bot

front/src/components/Dialogs/TaskImportDialog.vue, front/src/ctfnote/parsers/angstrom.ts, front/src/ctfnote/parsers/cini.ts, front/src/ctfnote/parsers/ctfd.ts, front/src/ctfnote/parsers/hitcon.ts, front/src/ctfnote/parsers/htb.ts, front/src/ctfnote/parsers/index.ts, front/src/ctfnote/parsers/justctf.ts, front/src/ctfnote/parsers/pico.ts, front/src/ctfnote/parsers/raw.ts
Now we just try to parse the input with each parser, ignoring errors. Then we select the parser with the most parsed challenges, except for some conditions with the raw parser. The raw parser will see every newline as a new task and when pasting a beautified JSON object, it should not be the best parser when other parsers also detect challenges.
The `isValid` function is now dropped which simplifies creating a parser.
This PR implements the logic as described in https://github.com/TFNS/CTFNote/issues/269#issuecomment-2158615590.
Screenshots:
=> Parser logic improvements

docker-compose.dev.yml, docker-compose.yml
This stops auto-booting the docker containers even after stopping the contains manually. So a manual trigger to stop the containers will now fully stop CTFNote from running. If not stopped manually, it will still restart.
=> Update docker-compose restart policy to `unless-stopped`

front/src/components/CTF/Guests.vue
When  you have a lot of accounts, it becomes difficult to find specific users in the list of chips. With the search possibility you can now filter the list to find specific users without using ctrl+f in your browser.
=> Add possibility to search for guests in invites

README.md
There was a typo and now we make the first two words bold so people won't skip it hopefully.
=> Fix .env copy instructions

api/src/routes/ical.ts
This PR adds two features to the iCal endpoint:
- use ctf id and pad domain as persistent UID
- currently a UUID is generated for each request
- the [spec](https://www.rfc-editor.org/rfc/rfc5545#section-3.8.4.7) requires the UID to be persistent
- add ctftime_url as ATTACH
- this allows to retrieve more information about the ctf from ctftime
=> Improve iCal endpoint

api/src/discord/agile/hooks.ts, front/src/components/Dialogs/TaskImportDialog.vue
Since we do not support batch importing tasks, the frontend spams the backend with a lot of task creations.
Due to throttling from Discord, it fails to create the extra Discord category for 50+ challenges.
This will break the channel creation.
So the fix for this without supporting batch import, is to import with batches from 10 where each first task is done in serial and the other 9 in parallel.
=> Fix 50 plus category creation discord bot

.github/workflows/ci.yml, api/migrations/56-assign-users-to-task.sql, api/src/discord/agile/hooks.ts, front/graphql.schema.json, front/src/components/Task/TaskAssignDialog.vue, front/src/components/Task/TaskMenu.vue, front/src/ctfnote/profiles.ts, front/src/ctfnote/tasks.ts, front/src/generated/graphql.ts, front/src/graphql/Assign.graphql
Now a manager or admin can assign tasks to other users. So task assignment can be triggered by someone else instead of only your own account.
- Implemented TaskAssignDialog.vue to allow task assignment to team members.
- Integrated member selection and assignment logic using GraphQL mutations.
- Updated TaskMenu.vue to include an option for assigning tasks for admins and managers.
- Defined GraphQL mutations for assigning and unassigning users in Assign.graphql.
=> feat: Add TaskAssignDialog component for assigning users to tasks
